# Lab 1 - Python Lab
## Author: *Lamae Maharaj*
## Date: 11:59 PM February 13, 2022

You should have access to a Notebook software that can edit and run `.ipynb` files. Prefereably, I recommend using Jupyter Notebook through the [Anaconda package](https://docs.anaconda.com/anaconda/install/index.html). You will write code in places marked "TO-DO" to complete the problems. Most of this will be a pure programming assignment but there are some questions that instead ask you to "write a few sentences". This is a writing class afterall. The tools for the solutions to these probelms can be found in the class python practice lectures. I encourage you to use Google and to flex your Google-Fu skills, but you should be learning. If you copy and paste esoteric code you don't understand, you're only cheating youself.

To "hand in" this lab, you should first download this file. The best way to do this is by cloning the class repository, solving it on your local device, then copying this file into your personal class repository on Github. For the student's convenience I will upload the Python Labs and Practice Lectures onto the Slack channel. 

Work on this with your friends! Programming is often a collaborative effort.

### Basic Python Skills

1. Print out the numerical constant pi with ten digits after the decimal point using the internal constant `pi`.

In [4]:
# Some packages I used. 
import numpy as np
import math as mth
import pandas as pd
import random as rn
from scipy.stats import percentileofscore

In [5]:
# TO-DO
float(format(np.pi,".10f"))

3.1415926536

2. Sum up the first 103 terms of the series 1 + 1/2 + 1/4 + 1/8 + ...

In [6]:
# TO-DO
sum([1/(2 ** i) for i in range(0, 103 + 1)])

2.0

3. Find the product of the first 37 terms in the sequence 1/3, 1/6, 1/9  ...

In [ ]:
# TO-DO
np.prod(1/np.arange(3,112,3))

4. Find the product of the first 387 terms of `1 * 1/2 * 1/4 * 1/8 *` ...

In [7]:
# TO-DO
np.prod(1/np.arange(2,776,2))

0.0

5. Is this answer *exactly* correct? 

No, it is not exactly correct. This computation experienced a numerical underflow. 

6. Figure out a means to express the answer more exactly. Not compute exactly, but express more exactly.

In [8]:
# TO-DO
-np.log(2)-sum(range(0,103))

-5253.69314718056

7. Create the sequence `x = [Inf, 20, 18, ..., -20]`.

In [9]:
# TO-DO
x = np.arange(-20,24,2,dtype=float)
x = np.flip(x)
x[0] = np.inf
x

array([ inf,  20.,  18.,  16.,  14.,  12.,  10.,   8.,   6.,   4.,   2.,
         0.,  -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18., -20.])

8. Create the sequence `x = [log_3(Inf), log_3(100), log_3(98), ... log_3(-20)]`.

In [10]:
# TO-DO
x = np.arange(-20,104,2,dtype=float)
x = np.flip(x)
x[0] = np.inf
x = np.log(x)
x

/var/folders/xw/c8nf8wyj3lg6zyzwz8lc32xr0000gn/T/ipykernel_64383/2258577920.py:5: RuntimeWarning: divide by zero encountered in log
  x = np.log(x)
/var/folders/xw/c8nf8wyj3lg6zyzwz8lc32xr0000gn/T/ipykernel_64383/2258577920.py:5: RuntimeWarning: invalid value encountered in log
  x = np.log(x)


array([       inf, 4.60517019, 4.58496748, 4.56434819, 4.54329478,
       4.52178858, 4.49980967, 4.47733681, 4.4543473 , 4.4308168 ,
       4.40671925, 4.38202663, 4.35670883, 4.33073334, 4.30406509,
       4.27666612, 4.24849524, 4.21950771, 4.18965474, 4.15888308,
       4.12713439, 4.09434456, 4.06044301, 4.02535169, 3.98898405,
       3.95124372, 3.91202301, 3.87120101, 3.8286414 , 3.78418963,
       3.73766962, 3.68887945, 3.63758616, 3.58351894, 3.52636052,
       3.4657359 , 3.40119738, 3.33220451, 3.25809654, 3.17805383,
       3.09104245, 2.99573227, 2.89037176, 2.77258872, 2.63905733,
       2.48490665, 2.30258509, 2.07944154, 1.79175947, 1.38629436,
       0.69314718,       -inf,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan])

9. Comment on the appropriateness of the non-numeric values.

NAN occurs because you cannot take the log of a negative number.
-Inf occurs when you take the log of 0.

10. Create a vector of booleans where the entry is true if `x[i]` is positive and finite.

In [11]:
# TO-DO
y = np.array([i>0 and np.isfinite(i) for i in x])
y

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False])

11. Locate the indices of the non-real numbers in this vector. Hint: use the `help` function. Don't hesitate to use the documentation via `help()`.

In [12]:
# TO-DO
np.where(y==np.iscomplex(y))

(array([ 0, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61]),)

12. Locate the indices of the infinite quantities in this vector. 

In [13]:
# TO-DO
print("This is where negative infinity exists:",np.where(x==-np.inf))
print("This is where positive infinity exists:",np.where(x==np.inf))

This is where negative infinity exists: (array([51]),)
This is where positive infinity exists: (array([0]),)


13. Locate the indices of the min and max in this vector.

In [14]:
# TO-DO
print("The maximum value is:", max(x))
print("The minimym value is:", min(x))

The maximum value is: inf
The minimym value is: -inf


14. Count the number of unique values in `x`.

In [15]:
# TO-DO
len(np.unique(x))

62

15. Cast `x` to a factor. Do the number of levels make sense?

In [16]:
# TO-DO
x = pd.to_numeric(x)
x 

array([       inf, 4.60517019, 4.58496748, 4.56434819, 4.54329478,
       4.52178858, 4.49980967, 4.47733681, 4.4543473 , 4.4308168 ,
       4.40671925, 4.38202663, 4.35670883, 4.33073334, 4.30406509,
       4.27666612, 4.24849524, 4.21950771, 4.18965474, 4.15888308,
       4.12713439, 4.09434456, 4.06044301, 4.02535169, 3.98898405,
       3.95124372, 3.91202301, 3.87120101, 3.8286414 , 3.78418963,
       3.73766962, 3.68887945, 3.63758616, 3.58351894, 3.52636052,
       3.4657359 , 3.40119738, 3.33220451, 3.25809654, 3.17805383,
       3.09104245, 2.99573227, 2.89037176, 2.77258872, 2.63905733,
       2.48490665, 2.30258509, 2.07944154, 1.79175947, 1.38629436,
       0.69314718,       -inf,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan])

16. Cast `x` to integers. What do we learn about R's infinity representation in the integer data type?

In [17]:
# TO-DO
x.astype(int)

# I learned that Python's infinity representation in the integer turns into -9223372036854775808 being its standard
# for both -inf and inf. 

array([-9223372036854775808,                    4,                    4,
                          4,                    4,                    4,
                          4,                    4,                    4,
                          4,                    4,                    4,
                          4,                    4,                    4,
                          4,                    4,                    4,
                          4,                    4,                    4,
                          4,                    4,                    4,
                          3,                    3,                    3,
                          3,                    3,                    3,
                          3,                    3,                    3,
                          3,                    3,                    3,
                          3,                    3,                    3,
                          3,                    3, 

17. Use `x` to create a new vector `y` containing only the positive real numbers in x.

In [18]:
# TO-DO
y = [i  for i in x if i>0 and np.complex(i)]
y

/var/folders/xw/c8nf8wyj3lg6zyzwz8lc32xr0000gn/T/ipykernel_64383/1398241831.py:2: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = [i  for i in x if i>0 and np.complex(i)]


[inf,
 4.605170185988092,
 4.584967478670572,
 4.564348191467836,
 4.543294782270004,
 4.5217885770490405,
 4.499809670330265,
 4.477336814478207,
 4.454347296253507,
 4.430816798843313,
 4.406719247264253,
 4.382026634673881,
 4.356708826689592,
 4.330733340286331,
 4.30406509320417,
 4.276666119016055,
 4.248495242049359,
 4.219507705176107,
 4.189654742026425,
 4.1588830833596715,
 4.127134385045092,
 4.0943445622221,
 4.060443010546419,
 4.02535169073515,
 3.9889840465642745,
 3.9512437185814275,
 3.912023005428146,
 3.871201010907891,
 3.828641396489095,
 3.784189633918261,
 3.7376696182833684,
 3.6888794541139363,
 3.6375861597263857,
 3.58351893845611,
 3.5263605246161616,
 3.4657359027997265,
 3.4011973816621555,
 3.332204510175204,
 3.258096538021482,
 3.1780538303479458,
 3.091042453358316,
 2.995732273553991,
 2.8903717578961645,
 2.772588722239781,
 2.6390573296152584,
 2.4849066497880004,
 2.302585092994046,
 2.0794415416798357,
 1.791759469228055,
 1.3862943611198906,
 0.

18. Use the left rectangle method to numerically integrate x^2 from 0 to 1 with rectangle width size 1e-6.

In [19]:
# TO-DO
sum(np.arange(0,1-1e-6,1e-6)**2)*1e-6

0.3333318333355003

19. Calculate the average of 100 realizations of standard Bernoullis in one line using the `random` library.

In [20]:
# TO-DO
n = rn.randint(1,1)
p = rn.uniform(0,1)
np.mean(np.random.binomial(n, p, size=100))

0.44

20. Calculate the average of 500 realizations of Bernoullis with p = 0.9.

In [21]:
# TO-DO
np.mean(np.random.binomial(n, 0.9, size=500))

0.912

21. Calculate the average of 1000 realizations of Bernoullis with p = 0.9.

In [22]:
# TO-DO
S = np.random.binomial(n, 0.9, size=1000)
np.mean(S)

0.885

23. Convert this variable into three binary variables without any information loss and put them into a data matrix.

In [ ]:
# TO-DO

24. What should the sum of each row be (in English)? 



25. Verify that. 

In [ ]:
# TO-DO

26. How should the column sum look (in English)? 



27. Verify that.

In [ ]:
# TO-DO

28. Generate a Pandas DataFrame with 100 rows where:

* The first column is realization from a normal with mean 17 and variance 38.
* The second column is uniform between -10 and 10.
* The third column is poisson with mean 6.
* The fourth column in exponential with lambda of 9.
* The fifth column is binomial with n = 20 and p = 0.12.
* and the sixth column is a binary variable with exactly 24% 1's dispersed randomly.

Name the rows the entries of the `fake_first_names` list.

In [23]:
fake_first_names = ["Sophia", "Emma", "Olivia", "Ava", "Mia", "Isabella", "Riley", 
  "Aria", "Zoe", "Charlotte", "Lily", "Layla", "Amelia", "Emily", 
  "Madelyn", "Aubrey", "Adalyn", "Madison", "Chloe", "Harper", 
  "Abigail", "Aaliyah", "Avery", "Evelyn", "Kaylee", "Ella", "Ellie", 
  "Scarlett", "Arianna", "Hailey", "Nora", "Addison", "Brooklyn", 
  "Hannah", "Mila", "Leah", "Elizabeth", "Sarah", "Eliana", "Mackenzie", 
  "Peyton", "Maria", "Grace", "Adeline", "Elena", "Anna", "Victoria", 
  "Camilla", "Lillian", "Natalie", "Jackson", "Aiden", "Lucas", 
  "Liam", "Noah", "Ethan", "Mason", "Caden", "Oliver", "Elijah", 
  "Grayson", "Jacob", "Michael", "Benjamin", "Carter", "James", 
  "Jayden", "Logan", "Alexander", "Caleb", "Ryan", "Luke", "Daniel", 
  "Jack", "William", "Owen", "Gabriel", "Matthew", "Connor", "Jayce", 
  "Isaac", "Sebastian", "Henry", "Muhammad", "Cameron", "Wyatt", 
  "Dylan", "Nathan", "Nicholas", "Julian", "Eli", "Levi", "Isaiah", 
  "Landon", "David", "Christian", "Andrew", "Brayden", "John", 
  "Lincoln"]

# TO-DO
n = 100
col1 = np.array(np.random.normal(17,38,n))
col2 = np.array(np.random.uniform(-10,10,n))
col3 = np.array(np.random.poisson(6,n))
col4 = np.array(np.random.exponential(9,n))
col5 = np.array(np.random.binomial(20,0.12,n))
col6 = np.random.binomial(1, 0.24, size=n)

29. Create a data frame of the same data as above except make the binary variable a factor "DOMESTIC" vs "FOREIGN" for 0 and 1 respectively. Use RStudio's `View` function to ensure this worked as desired.

In [24]:
# TO-DO
df = pd.DataFrame({'Realization' : pd.Series(col1, index =fake_first_names ),
                  'Uniform' : pd.Series(col2, index = fake_first_names ),
                  'Poisson' : pd.Series(col3, index = fake_first_names ),
                  'Exponential':pd.Series(col4, index = fake_first_names ),
                  'Binomial': pd.Series(col5, index = fake_first_names ),
                  'Binary': pd.Series(col6, index = fake_first_names )})

df['Binary'] = df['Binary'].replace(0,'DOMESTIC')
df['Binary'] = df['Binary'].replace(1,'FOREIGN')

df

Realization   Uniform  Poisson  Exponential  Binomial    Binary
Sophia       23.177852 -7.931948        6     3.059147         4   FOREIGN
Emma          6.208732  2.353540        8     0.592425         2  DOMESTIC
Olivia       71.980159  7.658680        3     5.339675         4  DOMESTIC
Ava          -0.440179  3.325740        3     7.605779         3   FOREIGN
Mia          -5.703577 -3.860062        6    10.139036         3  DOMESTIC
...                ...       ...      ...          ...       ...       ...
Christian     2.879641  3.495297        7     2.750695         0  DOMESTIC
Andrew       22.882727  9.833486        7     2.195155         1  DOMESTIC
Brayden      23.577317 -9.007030        8     7.018624         1   FOREIGN
John        -34.721386 -1.759169        5     9.176371         2  DOMESTIC
Lincoln      56.228591 -1.957809        6     4.055153         2  DOMESTIC

[100 rows x 6 columns]

30. Print out a table of the binary variable. Then print out the proportions of "DOMESTIC" vs "FOREIGN".

In [25]:
# TO-DO
df['Binary'].value_counts()

DOMESTIC    81
FOREIGN     19
Name: Binary, dtype: int64

31. Print out a summary of the whole dataframe.

In [26]:
# TO-DO
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, Sophia to Lincoln
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Realization  100 non-null    float64
 1   Uniform      100 non-null    float64
 2   Poisson      100 non-null    int64  
 3   Exponential  100 non-null    float64
 4   Binomial     100 non-null    int64  
 5   Binary       100 non-null    object 
dtypes: float64(3), int64(2), object(1)
memory usage: 5.5+ KB


32. Output summary statistics of the DataFrame.

In [27]:
# To-DO
df.describe()

Realization     Uniform     Poisson  Exponential    Binomial
count   100.000000  100.000000  100.000000   100.000000  100.000000
mean     12.706137   -0.065104    6.200000     7.502188    2.340000
std      38.684983    5.701646    2.502524     7.625608    1.478602
min     -95.003856   -9.767369    0.000000     0.059747    0.000000
25%     -15.214030   -4.937219    4.000000     2.709198    1.000000
50%      13.861675   -0.124324    6.000000     5.295303    2.000000
75%      42.166759    4.205783    7.250000    10.181203    3.000000
max      95.723963    9.880126   13.000000    42.810610    6.000000

33. Let `n = 50`. Create a n x n matrix `A` of exactly 50% entries 0's, 25% 1's 25% 2's. These values should be in random locations.

In [28]:
# TO-DO
p1 = 0.5
p2 = 0.25
p3 = 0.25
z = np.random.choice([0, 1, 2], size=(50, 50), p=[p1, p2, p3])
z = z*1.0
z

array([[2., 0., 2., ..., 2., 0., 0.],
       [1., 1., 0., ..., 2., 2., 0.],
       [0., 1., 0., ..., 2., 2., 1.],
       ...,
       [2., 2., 2., ..., 0., 2., 2.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 2.]])

34. Randomly punch holes (i.e. `NAN`) values in this matrix so that an each entry is missing with probability 30%. Hint: NumPy has a `np.nan` function.

In [36]:
# TO-DO
n = 30
index = np.random.choice(z.size,n,replace=False)
z.ravel()[index] = np.nan
z

array([[ 2.,  0.,  2., ...,  2.,  0.,  0.],
       [ 1.,  1.,  0., ...,  2.,  2.,  0.],
       [ 0.,  1.,  0., ...,  2.,  2.,  1.],
       ...,
       [ 2.,  2.,  2., ..., nan,  2.,  2.],
       [ 0.,  1.,  0., ...,  0.,  0.,  1.],
       [ 0.,  1.,  0., ...,  1.,  0.,  2.]])

35. Sort the rows in matrix `A` by the largest row sum to lowest. Be careful about the NAN's!

In [37]:
# TO-DO
z[:,np.argsort(z.sum(axis=0))[::-1]]

array([[ 0.,  2., nan, ...,  0.,  2.,  2.],
       [ 0.,  1.,  0., ...,  2.,  1.,  0.],
       [ 1.,  2., nan, ...,  0.,  0.,  1.],
       ...,
       [ 2.,  2.,  2., ...,  1.,  2.,  0.],
       [ 1.,  0.,  2., ...,  0.,  0.,  0.],
       [ 2.,  2.,  0., ...,  0.,  0.,  1.]])

36. Set a seed and then create a list `v` consisting of a sample of 1,000 iid normal realizations with mean -10 and variance 100.

In [38]:
# TO-DO
rn.seed(10)
v = np.random.normal(-10,100,1000)

37. Repeat (36) with a new seed. Save this new result to `w`.

In [40]:
# TO-DO
rn.seed(20)
v = np.random.normal(-10,100,1000)

38. Find the average of `v` and the standard error of `v`.

In [41]:
# TO-DO
print("The mean of v is:",np.mean(v))
print("The standard error of v is:",np.std(v,ddof=1)/np.sqrt(np.size(v)))

The mean of v is: -10.53139221982094
The standard error of v is: 3.1283053111367334


39. Find the 5%ile of `v` using the Numpy library, read documentation to figure out which function to use. Is the estimate about what is expected by theory?

In [42]:
# TO-DO
np.percentile(v,5)

-174.22064971927443

40. What is the percentile of `v` that corresponds to the value 0? What should it be theoretically? Is the estimate about what is expected by theory?

In [43]:
# TO-DO
print("The percentile of v that corresponds with the value of 0 is:",percentileofscore(v, 0),"%")

The percentile of v that corresponds with the value of 0 is: 54.7 %
